### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by jmillerdesign** [mhkeller/joiner#11]
`report.prose.full` needs a default value, because it's possible to reach [joiner.node.js#L4080](https://github.com/mhkeller/joiner/blob/master/dist/joiner.node.js#L4080) without it being a string. This causes an error, because you can't call `.trim()` on `undefined`.

**Comment by keesvanbemmel** [comment]
How did you solve this in the meantime?

**Comment by mhkeller** [comment]
Sorry about that. The fix would be to just make the default object be the below structure. The issue is that uglifyjs has been deprecated and they pulled their code from npm so I need to redo the build setup to publish a new version.

```
  var report = {
    diff: {},
    prose: {
      summary: '',
      full: ''
    }
  }
```

**Comment by mhkeller** [comment]
I just pushed version 2.1.3 to npm, which should fix things. Let me know how that goes with your use case. If you have a barebones reproduction of the files you're using, too, that would be great to add as a test.

**Comment by mhkeller** [comment]
^^@jmillerdesign + @keesvanbemmel

**Comment by keesvanbemmel** [comment]
Thanks! I'm afraid I can't share these files as they contain sensitive data. However, it occurs when the key which is used in the same files all occur. So no mismatches, everything matches up.

**Comment by mhkeller** [comment]
Got it. If you can sanitize them and use an example with two or three rows that just uses "a", "b", and "c" for keys that would be helpful .
